export type EventCategory = 'Workshop' | 'Teacher Training' | 'Dharma Talk' | 'Conference';

export interface YogaEvent {
  id: string;
  title: string;
  category: EventCategory;
  date: string; // ISO YYYY-MM-DD
  endDate?: string; // ISO YYYY-MM-DD
  time: string;
  endTime: string;
  location: string;
  isOnline: boolean;
  price: number | 'Free';
  description: string;
  instructor: string;
  spots: number | null;
  organizer?: string;
  organizerBio?: string;
  organizerAvatar?: string;
  externalUrl?: string;
  timezone?: string;
  venue?: string;
  capacity?: number;
  spotsRemaining?: number;
}

export const events: YogaEvent[] = [
  {
    id: 'vinyasa-flow-workshop',
    title: 'Vinyasa Flow Masterclass',
    category: 'Workshop',
    date: '2026-03-20',
    time: '10:00',
    endTime: '12:30',
    location: 'Online (Zoom)',
    isOnline: true,
    price: 25,
    description: 'A deep dive into the art of sequencing in Vinyasa yoga. Learn how to build intelligent, creative flows that honor anatomy and serve diverse bodies. Suitable for teachers and advanced students.',
    instructor: 'Priya Sharma',
    spots: 40,
  },
  {
    id: 'teacher-training-info',
    title: '200-Hour Teacher Training: Info Session',
    category: 'Teacher Training',
    date: '2026-03-22',
    time: '18:00',
    endTime: '19:30',
    location: 'Online (Zoom)',
    isOnline: true,
    price: 'Free',
    description: 'Join us for an open information session about GOYA-accredited 200-hour teacher training programs. Ask questions, meet lead trainers, and learn about the application process.',
    instructor: 'GOYA Team',
    spots: null,
  },
  {
    id: 'dharma-eight-limbs',
    title: 'Dharma Talk: The Eight Limbs of Yoga',
    category: 'Dharma Talk',
    date: '2026-03-25',
    time: '19:00',
    endTime: '20:30',
    location: 'Online (YouTube Live)',
    isOnline: true,
    price: 'Free',
    description: 'An accessible and inspiring journey through Patanjali\'s Ashtanga — the eight-limbed path of yoga. Open to all levels. No prior philosophy background required.',
    instructor: 'Kenji Nakamura',
    spots: null,
  },
  {
    id: 'yin-yoga-masterclass',
    title: 'Yin Yoga & Meridian Theory Immersion',
    category: 'Workshop',
    date: '2026-03-28',
    time: '09:00',
    endTime: '17:00',
    location: 'London, United Kingdom',
    isOnline: false,
    price: 95,
    description: 'A full-day immersion exploring Yin Yoga through the lens of Traditional Chinese Medicine. Learn how meridian theory can inform your practice and teaching. Includes lunch and course materials.',
    instructor: 'Freya Andersen',
    spots: 20,
  },
  {
    id: 'goya-conference-2026',
    title: 'GOYA Annual Conference 2026',
    category: 'Conference',
    date: '2026-04-05',
    time: '08:00',
    endTime: '18:00',
    location: 'Bali, Indonesia',
    isOnline: false,
    price: 195,
    description: 'The flagship annual gathering of the GOYA community. Three days of keynotes, workshops, networking, and community practice. Early bird pricing available until March 31.',
    instructor: 'Various Speakers',
    spots: 300,
  },
  {
    id: 'pranayama-workshop',
    title: 'Pranayama & Breathwork Workshop',
    category: 'Workshop',
    date: '2026-04-08',
    time: '18:30',
    endTime: '20:30',
    location: 'Online (Zoom)',
    isOnline: true,
    price: 30,
    description: 'An evidence-based exploration of breathwork techniques — from classical pranayama to contemporary breath science. Participants will leave with a practical toolkit for daily practice.',
    instructor: 'Sarah Mitchell',
    spots: 35,
  },
  {
    id: '500hr-orientation',
    title: '500-Hour Advanced Training: Orientation',
    category: 'Teacher Training',
    date: '2026-04-12',
    time: '17:00',
    endTime: '18:30',
    location: 'Online (Zoom)',
    isOnline: true,
    price: 'Free',
    description: 'Explore pathways to your 500-hour certification through GOYA-accredited schools. Hear from alumni, lead trainers, and the GOYA standards committee.',
    instructor: 'GOYA Academy',
    spots: null,
  },
  {
    id: 'dharma-yoga-sutras',
    title: 'Dharma Talk: Yoga Sutras for Modern Life',
    category: 'Dharma Talk',
    date: '2026-04-15',
    time: '19:30',
    endTime: '21:00',
    location: 'Online (YouTube Live)',
    isOnline: true,
    price: 'Free',
    description: 'What do Patanjali\'s Yoga Sutras have to teach us about navigating modern challenges? A practical and philosophical discussion open to all.',
    instructor: 'Amara Osei',
    spots: null,
  },
  {
    id: 'restorative-immersion',
    title: 'Restorative Yoga Weekend Immersion',
    category: 'Workshop',
    date: '2026-04-20',
    time: '10:00',
    endTime: '17:00',
    location: 'Barcelona, Spain',
    isOnline: false,
    price: 140,
    description: 'Two days of deep rest, nervous system regulation, and restorative yoga practice. Suitable for practitioners seeking burnout recovery and for teachers wishing to add restorative skills to their offerings.',
    instructor: 'Elena Vasquez',
    spots: 15,
  },
  {
    id: 'kids-yoga-training',
    title: 'Children\'s Yoga Teacher Training',
    category: 'Teacher Training',
    date: '2026-05-03',
    time: '09:00',
    endTime: '17:00',
    location: 'Online (Zoom)',
    isOnline: true,
    price: 350,
    description: 'A GOYA-accredited 30-hour children\'s yoga training. Learn age-appropriate sequencing, classroom management, storytelling techniques, and ethical considerations when working with minors.',
    instructor: 'Freya Andersen',
    spots: 25,
  },

  // ── 20 NEW EVENTS ──────────────────────────────────────────────────────────

  // WORKSHOPS (6)
  {
    id: 'yin-immersion-vancouver-apr',
    title: 'Yin Yoga Immersion Weekend',
    category: 'Workshop',
    date: '2026-04-12',
    endDate: '2026-04-13',
    time: '09:00',
    endTime: '17:00',
    location: 'Vancouver, BC, Canada',
    isOnline: false,
    venue: 'Eastside Yoga Studio, 1234 Commercial Dr, Vancouver',
    price: 185,
    description: 'A deep immersion into the world of Yin Yoga over two full days with senior teacher Ethan Murphy. Explore long-held postures targeting fascia and connective tissue, combined with insights from Taoist philosophy and Traditional Chinese Medicine.',
    instructor: 'Ethan Murphy',
    organizer: 'Ethan Murphy',
    organizerBio: 'Ethan is a Vancouver-based Yin Yoga and meditation teacher with 12 years of experience in Traditional Chinese Medicine-informed practice.',
    organizerAvatar: 'https://randomuser.me/api/portraits/men/8.jpg',
    externalUrl: 'https://example.com/events/yin-immersion-vancouver',
    timezone: 'America/Vancouver',
    capacity: 24,
    spotsRemaining: 7,
    spots: 7,
  },
  {
    id: 'arm-balance-austin-may',
    title: 'Arm Balances & Inversions Intensive',
    category: 'Workshop',
    date: '2026-05-09',
    endDate: '2026-05-10',
    time: '10:00',
    endTime: '16:00',
    location: 'Austin, TX, USA',
    isOnline: false,
    venue: 'South Congress Yoga Collective, 2400 S Congress Ave, Austin',
    price: 120,
    description: 'Demystify arm balances and inversions over two days. Build the strength, alignment awareness, and confidence to safely explore Crow, Handstand, Forearm Stand, and more. Open to intermediate and advanced practitioners.',
    instructor: 'Jennifer Walsh',
    organizer: 'Jennifer Walsh',
    organizerBio: 'Jennifer has been teaching Vinyasa and Power Yoga in Manhattan for twelve years, known for dynamic sequencing and accessible challenges.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    externalUrl: 'https://example.com/events/arm-balance-austin',
    timezone: 'America/Chicago',
    capacity: 30,
    spotsRemaining: 14,
    spots: 14,
  },
  {
    id: 'sound-healing-london-may',
    title: 'Sound Healing & Yoga Nidra Workshop',
    category: 'Workshop',
    date: '2026-05-17',
    time: '14:00',
    endTime: '18:00',
    location: 'London, United Kingdom',
    isOnline: false,
    venue: 'Triyoga Camden, 57 Jamestown Rd, London NW1',
    price: 65,
    description: 'Experience the therapeutic power of sound healing combined with Yoga Nidra. Crystal singing bowls, gongs, and guided meditation create a deeply restorative afternoon. No experience necessary.',
    instructor: 'Freya Andersen',
    organizer: 'Freya Andersen',
    organizerBio: 'Freya is a London-based sound healer and yoga teacher specializing in Yin Yoga and restorative practices.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    externalUrl: 'https://example.com/events/sound-healing-london',
    timezone: 'Europe/London',
    capacity: 35,
    spotsRemaining: 22,
    spots: 22,
  },
  {
    id: 'handstand-workshop-berlin-jun',
    title: 'Handstand Foundations Workshop',
    category: 'Workshop',
    date: '2026-06-06',
    time: '11:00',
    endTime: '14:00',
    location: 'Berlin, Germany',
    isOnline: false,
    venue: 'Yoga Werkstatt, Oranienstraße 25, Berlin',
    price: 55,
    description: 'A structured approach to Handstand for all levels. Learn drills, wall progressions, spotting techniques, and the biomechanics behind a solid inversion practice. Small group setting ensures personalized attention.',
    instructor: 'Lars Petersen',
    organizer: 'Lars Petersen',
    organizerBio: 'Lars is a Berlin-based Ashtanga teacher and movement coach with a background in gymnastics and physical therapy.',
    organizerAvatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    externalUrl: 'https://example.com/events/handstand-berlin',
    timezone: 'Europe/Berlin',
    capacity: 16,
    spotsRemaining: 5,
    spots: 5,
  },
  {
    id: 'ashtanga-intensive-sydney-jun',
    title: 'Ashtanga Primary Series Intensive',
    category: 'Workshop',
    date: '2026-06-20',
    endDate: '2026-06-21',
    time: '06:00',
    endTime: '12:00',
    location: 'Sydney, NSW, Australia',
    isOnline: false,
    venue: 'Bondi Yoga House, 72 Campbell Parade, Bondi Beach',
    price: 160,
    description: 'Two mornings of deep Mysore-style practice with detailed instruction on the Primary Series. Includes anatomy breakdowns, adjustment clinics, and a philosophy discussion on the Ashtanga lineage.',
    instructor: 'Amara Osei',
    organizer: 'Amara Osei',
    organizerBio: 'Amara teaches traditional Ashtanga in the Mysore style and has studied in Mysore, India for five consecutive years.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    externalUrl: 'https://example.com/events/ashtanga-sydney',
    timezone: 'Australia/Sydney',
    capacity: 20,
    spotsRemaining: 11,
    spots: 11,
  },
  {
    id: 'meditation-online-apr',
    title: 'Meditation for Beginners: 4-Week Course',
    category: 'Workshop',
    date: '2026-04-20',
    endDate: '2026-05-11',
    time: '19:00',
    endTime: '20:15',
    location: 'Online (Zoom)',
    isOnline: true,
    venue: 'Online via Zoom',
    price: 80,
    description: 'A gentle four-week introduction to seated meditation. Each session covers a different technique — mindfulness, loving-kindness, body scan, and mantra — with take-home practices. Recordings provided.',
    instructor: 'Kenji Nakamura',
    organizer: 'Kenji Nakamura',
    organizerBio: 'Kenji is a Zen practitioner and meditation teacher based in Kyoto, now teaching worldwide via online programs.',
    organizerAvatar: 'https://randomuser.me/api/portraits/men/36.jpg',
    externalUrl: 'https://example.com/events/meditation-beginners',
    timezone: 'America/New_York',
    capacity: 60,
    spotsRemaining: 33,
    spots: 33,
  },

  // TEACHER TRAININGS (5)
  {
    id: '200hr-tt-bali-apr',
    title: '200-Hour Vinyasa Teacher Training — Bali',
    category: 'Teacher Training',
    date: '2026-04-15',
    endDate: '2026-05-10',
    time: '07:00',
    endTime: '18:00',
    location: 'Ubud, Bali, Indonesia',
    isOnline: false,
    venue: 'Yoga Barn, Jl. Raya Pengosekan, Ubud',
    price: 2800,
    description: 'A life-changing 26-day immersive 200-hour teacher training in the heart of Ubud. Curriculum covers asana methodology, anatomy, philosophy, pranayama, meditation, and practicum teaching. Yoga Alliance certified.',
    instructor: 'Priya Sharma',
    organizer: 'Priya Sharma',
    organizerBio: 'Priya is an E-RYT 500 lead trainer who has graduated over 400 teachers across programs in India, Bali, and Europe.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/65.jpg',
    externalUrl: 'https://example.com/events/200hr-bali',
    timezone: 'Asia/Makassar',
    capacity: 22,
    spotsRemaining: 4,
    spots: 4,
  },
  {
    id: '300hr-tt-online-may',
    title: '300-Hour Advanced Teacher Training — Online',
    category: 'Teacher Training',
    date: '2026-05-01',
    endDate: '2026-08-31',
    time: '09:00',
    endTime: '13:00',
    location: 'Online (Zoom)',
    isOnline: true,
    venue: 'Online via Zoom',
    price: 2200,
    description: 'A four-month part-time 300-hour advanced training for existing RYT-200 teachers. Modules include advanced anatomy, therapeutic yoga, business of yoga, mentorship, and 50 hours of practicum. Weekend intensives plus weekly live sessions.',
    instructor: 'Sarah Mitchell',
    organizer: 'Sarah Mitchell',
    organizerBio: 'Sarah is an E-RYT 500 and YACEP with a background in physiotherapy, specializing in anatomy education for yoga teachers.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/33.jpg',
    externalUrl: 'https://example.com/events/300hr-online',
    timezone: 'America/New_York',
    capacity: 30,
    spotsRemaining: 18,
    spots: 18,
  },
  {
    id: 'prenatal-tt-austin-jun',
    title: 'Prenatal Yoga Teacher Training (85hr)',
    category: 'Teacher Training',
    date: '2026-06-08',
    endDate: '2026-06-19',
    time: '08:30',
    endTime: '17:30',
    location: 'Austin, TX, USA',
    isOnline: false,
    venue: 'Mama Flow Studio, 1800 E 6th St, Austin',
    price: 1400,
    description: 'An 85-hour RPYT certification program covering prenatal anatomy, safe modifications, labor preparation yoga, postpartum recovery, and the emotional journey of pregnancy. Includes hands-on practicum with expecting mothers.',
    instructor: 'Elena Vasquez',
    organizer: 'Elena Vasquez',
    organizerBio: 'Elena is a midwife-turned-yoga-teacher specializing in perinatal wellness and women\'s health.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/55.jpg',
    externalUrl: 'https://example.com/events/prenatal-tt-austin',
    timezone: 'America/Chicago',
    capacity: 18,
    spotsRemaining: 9,
    spots: 9,
  },
  {
    id: 'trauma-informed-tt-online-jul',
    title: 'Trauma-Informed Yoga Facilitator Training',
    category: 'Teacher Training',
    date: '2026-07-06',
    endDate: '2026-07-24',
    time: '10:00',
    endTime: '14:00',
    location: 'Online (Zoom)',
    isOnline: true,
    venue: 'Online via Zoom',
    price: 950,
    description: 'A 40-hour training equipping yoga teachers to work safely with trauma survivors. Covers neuroscience of trauma, invitational language, consent-based assists, adaptive practices, and professional boundaries. Taught by a licensed therapist and yoga teacher.',
    instructor: 'Amara Osei',
    organizer: 'Amara Osei',
    organizerBio: 'Amara holds an MSW and E-RYT 500, bridging clinical social work and yoga in her teaching approach.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    externalUrl: 'https://example.com/events/trauma-informed-tt',
    timezone: 'America/New_York',
    capacity: 25,
    spotsRemaining: 16,
    spots: 16,
  },
  {
    id: 'yin-tt-london-aug',
    title: 'Yin Yoga Teacher Training (50hr)',
    category: 'Teacher Training',
    date: '2026-08-03',
    endDate: '2026-08-09',
    time: '09:00',
    endTime: '17:00',
    location: 'London, United Kingdom',
    isOnline: false,
    venue: 'The Life Centre, 15 Edge St, London W8',
    price: 750,
    description: 'A week-long 50-hour Yin Yoga training exploring fascial anatomy, meridian theory, and the art of stillness. Learn to sequence and teach Yin classes with confidence. Suitable for RYT-200 holders or experienced practitioners.',
    instructor: 'Freya Andersen',
    organizer: 'Freya Andersen',
    organizerBio: 'Freya has trained over 200 Yin Yoga teachers and is the author of "Stillness in Motion: A Yin Yoga Handbook."',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    externalUrl: 'https://example.com/events/yin-tt-london',
    timezone: 'Europe/London',
    capacity: 20,
    spotsRemaining: 8,
    spots: 8,
  },

  // DHARMA TALKS (4)
  {
    id: 'dharma-bhagavad-gita-mar',
    title: 'Dharma Talk: Lessons from the Bhagavad Gita',
    category: 'Dharma Talk',
    date: '2026-03-29',
    time: '18:00',
    endTime: '19:30',
    location: 'Online (YouTube Live)',
    isOnline: true,
    venue: 'Online via YouTube Live',
    price: 'Free',
    description: 'An open and accessible exploration of the Bhagavad Gita\'s teachings on duty, devotion, and the nature of self. How can an ancient warrior\'s dilemma illuminate our modern struggles? Open to all, no prior reading required.',
    instructor: 'Kenji Nakamura',
    organizer: 'Kenji Nakamura',
    organizerBio: 'Kenji weaves together Zen Buddhism and Vedantic philosophy in his popular monthly dharma talk series.',
    organizerAvatar: 'https://randomuser.me/api/portraits/men/36.jpg',
    externalUrl: 'https://example.com/events/dharma-gita',
    timezone: 'America/New_York',
    spots: null,
  },
  {
    id: 'dharma-ahimsa-apr',
    title: 'Dharma Talk: Ahimsa — Non-Violence in Daily Life',
    category: 'Dharma Talk',
    date: '2026-04-05',
    time: '17:00',
    endTime: '18:30',
    location: 'Online (Zoom)',
    isOnline: true,
    venue: 'Online via Zoom',
    price: 15,
    description: 'A reflective session on the first Yama: Ahimsa. How do we practice non-violence toward ourselves, others, and the planet? Includes guided journaling and small-group discussion. Recording available afterward.',
    instructor: 'Priya Sharma',
    organizer: 'Priya Sharma',
    organizerBio: 'Priya brings 20 years of study in Indian philosophy to her dharma teachings, grounded in the Krishnamacharya lineage.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/65.jpg',
    externalUrl: 'https://example.com/events/dharma-ahimsa',
    timezone: 'America/Los_Angeles',
    spots: null,
  },
  {
    id: 'dharma-impermanence-apr',
    title: 'Dharma Talk: The Practice of Impermanence',
    category: 'Dharma Talk',
    date: '2026-04-19',
    time: '19:00',
    endTime: '20:30',
    location: 'Online (YouTube Live)',
    isOnline: true,
    venue: 'Online via YouTube Live',
    price: 'Free',
    description: 'Drawing from Buddhist and yogic traditions, this talk explores how embracing impermanence can transform our relationship with loss, change, and the passage of time. A contemplative evening with meditation and Q&A.',
    instructor: 'Amara Osei',
    organizer: 'Amara Osei',
    organizerBio: 'Amara integrates West African spiritual traditions with classical yoga philosophy in her teaching.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    externalUrl: 'https://example.com/events/dharma-impermanence',
    timezone: 'America/New_York',
    spots: null,
  },
  {
    id: 'dharma-yoga-ethics-may',
    title: 'Dharma Talk: Ethics, Power & the Yoga Industry',
    category: 'Dharma Talk',
    date: '2026-05-10',
    time: '18:00',
    endTime: '19:30',
    location: 'Online (Zoom)',
    isOnline: true,
    venue: 'Online via Zoom',
    price: 45,
    description: 'A candid panel discussion on ethics, accountability, and power dynamics in yoga spaces. Three experienced teachers share perspectives on harm reduction, cultural sensitivity, and building trust in yoga communities.',
    instructor: 'Panel: Priya Sharma, Amara Osei, Jennifer Walsh',
    organizer: 'GOYA Ethics Committee',
    organizerBio: 'The GOYA Ethics Committee works to uphold standards of integrity and accountability across the global yoga community.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/65.jpg',
    externalUrl: 'https://example.com/events/dharma-ethics',
    timezone: 'America/New_York',
    capacity: 100,
    spotsRemaining: 67,
    spots: 67,
  },

  // CONFERENCES (3)
  {
    id: 'yoga-fest-europe-jun',
    title: 'YogaFest Europe 2026',
    category: 'Conference',
    date: '2026-06-26',
    endDate: '2026-06-28',
    time: '08:00',
    endTime: '20:00',
    location: 'Barcelona, Spain',
    isOnline: false,
    venue: 'Fira de Barcelona, Av. de la Reina Maria Cristina, Barcelona',
    price: 295,
    description: 'Three days of workshops, keynotes, and community practice in the heart of Barcelona. Over 50 presenters covering Vinyasa, Ashtanga, Kundalini, Yin, philosophy, anatomy, and the business of yoga. Evening kirtan and community meals included.',
    instructor: 'Various Speakers',
    organizer: 'YogaFest International',
    organizerBio: 'YogaFest International produces large-scale yoga gatherings across Europe, Asia, and the Americas.',
    organizerAvatar: 'https://randomuser.me/api/portraits/men/52.jpg',
    externalUrl: 'https://example.com/events/yogafest-europe',
    timezone: 'Europe/Madrid',
    capacity: 800,
    spotsRemaining: 340,
    spots: 340,
  },
  {
    id: 'mindful-movement-summit-aug',
    title: 'Mindful Movement Summit',
    category: 'Conference',
    date: '2026-08-14',
    endDate: '2026-08-16',
    time: '09:00',
    endTime: '18:00',
    location: 'Denver, CO, USA',
    isOnline: false,
    venue: 'Colorado Convention Center, 700 14th St, Denver',
    price: 350,
    description: 'A cross-disciplinary summit bringing together yoga teachers, somatic therapists, movement scientists, and mindfulness researchers. Three days of lectures, movement labs, and panel discussions exploring the science of embodied awareness.',
    instructor: 'Various Speakers',
    organizer: 'Mindful Movement Foundation',
    organizerBio: 'The Mindful Movement Foundation bridges the gap between contemplative practice and movement science research.',
    organizerAvatar: 'https://randomuser.me/api/portraits/men/61.jpg',
    externalUrl: 'https://example.com/events/mindful-movement-summit',
    timezone: 'America/Denver',
    capacity: 500,
    spotsRemaining: 215,
    spots: 215,
  },
  {
    id: 'goya-asia-pacific-sep',
    title: 'GOYA Asia-Pacific Regional Conference',
    category: 'Conference',
    date: '2026-09-18',
    endDate: '2026-09-20',
    time: '08:30',
    endTime: '17:30',
    location: 'Singapore',
    isOnline: false,
    venue: 'Marina Bay Sands Expo, 10 Bayfront Ave, Singapore',
    price: 195,
    description: 'The inaugural GOYA Asia-Pacific conference bringing together teachers, schools, and wellness practitioners from across the region. Keynotes on yoga\'s future in Asia, breakout sessions on standards and accreditation, and networking events.',
    instructor: 'Various Speakers',
    organizer: 'GOYA Asia-Pacific Chapter',
    organizerBio: 'The GOYA Asia-Pacific Chapter serves the growing yoga community across Southeast Asia, East Asia, and Oceania.',
    organizerAvatar: 'https://randomuser.me/api/portraits/women/72.jpg',
    externalUrl: 'https://example.com/events/goya-asia-pacific',
    timezone: 'Asia/Singapore',
    capacity: 400,
    spotsRemaining: 280,
    spots: 280,
  },
];

export const allCategories: Array<'All' | EventCategory> = [
  'All', 'Workshop', 'Teacher Training', 'Dharma Talk', 'Conference',
];
