export type MemberRole = 'Teacher' | 'Student' | 'School' | 'Wellness Practitioner';

export interface Member {
  id: string;
  name: string;
  role: MemberRole;
  country: string;
  city: string;
  coordinates: [number, number]; // [lng, lat]
  bio: string;
  photo: string;
  designations: string[];
  teachingStyles: string[];
  specialties: string[];
  credits: {
    CE: number;
    Community: number;
    Karma: number;
    Practice: number;
  };
  social: {
    website?: string;
    instagram?: string;
    youtube?: string;
  };
  memberSince: string;
  featured?: boolean;
}

export const members: Member[] = [

  // ── TEACHERS (44) ───────────────────────────────────────────────────────────

  // United States – 13 teachers
  {
    id: 'jennifer-walsh',
    name: 'Jennifer Walsh',
    role: 'Teacher',
    country: 'United States',
    city: 'New York',
    coordinates: [-74.0060, 40.7128],
    bio: 'Jennifer has been teaching Vinyasa and Power Yoga in Manhattan for twelve years. She is known for her dynamic sequencing and her ability to make challenging practices accessible to students at every level.',
    photo: 'https://randomuser.me/api/portraits/women/2.jpg',
    designations: ['E-RYT 500', 'YACEP'],
    teachingStyles: ['Vinyasa', 'Power Yoga', 'Meditation'],
    specialties: ['Urban Wellness', 'Breath-Led Flow', 'Corporate Yoga'],
    credits: { CE: 220, Community: 75, Karma: 110, Practice: 1600 },
    social: { website: 'https://jenwalsyoga.com', instagram: '@jen.walsh.yoga' },
    memberSince: '2019',
    featured: true,
  },
  {
    id: 'michael-torres',
    name: 'Michael Torres',
    role: 'Teacher',
    country: 'United States',
    city: 'Los Angeles',
    coordinates: [-118.2437, 34.0522],
    bio: 'Michael blends Ashtanga precision with California coastal ease in his classes at a beachside studio in Venice. A former competitive athlete, he brings a deep understanding of biomechanics and recovery to his sequencing.',
    photo: 'https://randomuser.me/api/portraits/men/2.jpg',
    designations: ['E-RYT 500', 'YACEP'],
    teachingStyles: ['Ashtanga', 'Vinyasa', 'Pranayama'],
    specialties: ['Athletes', 'Injury Prevention', 'Advanced Asana'],
    credits: { CE: 280, Community: 60, Karma: 140, Practice: 2100 },
    social: { instagram: '@michael.torres.yoga', youtube: 'MichaelTorresYoga' },
    memberSince: '2018',
    featured: true,
  },
  {
    id: 'rachel-green',
    name: 'Rachel Green',
    role: 'Teacher',
    country: 'United States',
    city: 'Chicago',
    coordinates: [-87.6298, 41.8781],
    bio: 'Rachel teaches Yin and Restorative yoga at a downtown Chicago studio, drawing on a background in physical therapy to guide students safely into deep tissue release. She is passionate about slowing down in a city that never stops.',
    photo: 'https://randomuser.me/api/portraits/women/3.jpg',
    designations: ['E-RYT 200', 'RPYT'],
    teachingStyles: ['Yin', 'Restorative', 'Therapeutic'],
    specialties: ['Prenatal Yoga', 'Injury Recovery', 'Stress Relief'],
    credits: { CE: 160, Community: 80, Karma: 70, Practice: 1100 },
    social: { website: 'https://rachgreenyoga.com', instagram: '@rachel.green.yoga' },
    memberSince: '2020',
  },
  {
    id: 'david-kim',
    name: 'David Kim',
    role: 'Teacher',
    country: 'United States',
    city: 'San Francisco',
    coordinates: [-122.4194, 37.7749],
    bio: 'David integrates Kundalini technology and somatic awareness in his SF Bay Area classes and retreats. A former software engineer turned yoga teacher, he bridges mindfulness practice with the demands of tech-industry burnout.',
    photo: 'https://randomuser.me/api/portraits/men/3.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Kundalini', 'Meditation', 'Yoga Nidra'],
    specialties: ['Burnout Recovery', 'Breathwork', 'Mantra'],
    credits: { CE: 190, Community: 55, Karma: 100, Practice: 1400 },
    social: { instagram: '@davidkim.yoga', website: 'https://davidkimyoga.com' },
    memberSince: '2021',
  },
  {
    id: 'ashley-johnson',
    name: 'Ashley Johnson',
    role: 'Teacher',
    country: 'United States',
    city: 'Austin',
    coordinates: [-97.7431, 30.2672],
    bio: 'Ashley runs a thriving Hot Yoga studio in Austin and leads 200-hour teacher trainings twice a year. Her high-energy classes draw a devoted community of practitioners from across central Texas.',
    photo: 'https://randomuser.me/api/portraits/women/4.jpg',
    designations: ['E-RYT 500', 'YACEP', 'RYS 200'],
    teachingStyles: ['Hot Yoga', 'Vinyasa', 'Power Yoga'],
    specialties: ['Teacher Training', 'Heat Practice', 'Community Building'],
    credits: { CE: 300, Community: 120, Karma: 160, Practice: 2400 },
    social: { website: 'https://austinyogahouse.com', instagram: '@ashley.yoga.atx' },
    memberSince: '2019',
    featured: true,
  },
  {
    id: 'tyler-brooks',
    name: 'Tyler Brooks',
    role: 'Teacher',
    country: 'United States',
    city: 'Seattle',
    coordinates: [-122.3321, 47.6062],
    bio: 'Tyler teaches Hatha and meditation in Seattle with a focus on dharma and philosophy. He studied in Mysore for three seasons and brings a contemplative depth to his public classes and private sessions.',
    photo: 'https://randomuser.me/api/portraits/men/4.jpg',
    designations: ['E-RYT 500'],
    teachingStyles: ['Hatha', 'Meditation', 'Yoga Philosophy'],
    specialties: ['Classical Yoga', 'Dharma Talks', 'Retreat Facilitation'],
    credits: { CE: 240, Community: 90, Karma: 130, Practice: 1900 },
    social: { instagram: '@tylerbrooks.yoga', youtube: 'TylerBrooksYoga' },
    memberSince: '2018',
  },
  {
    id: 'olivia-martinez',
    name: 'Olivia Martinez',
    role: 'Teacher',
    country: 'United States',
    city: 'Portland',
    coordinates: [-122.6750, 45.5051],
    bio: 'Olivia is a trauma-sensitive yoga facilitator working with survivors of domestic violence and veterans in Portland. Her community-based approach prioritizes agency, safety, and healing over perfecting postures.',
    photo: 'https://randomuser.me/api/portraits/women/5.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Trauma-Sensitive Yoga', 'Gentle Yoga', 'Restorative'],
    specialties: ['Trauma Recovery', 'Veterans', 'Community Yoga'],
    credits: { CE: 175, Community: 200, Karma: 185, Practice: 980 },
    social: { instagram: '@olivia.yoga.pdx', website: 'https://healingyogapdx.org' },
    memberSince: '2020',
  },
  {
    id: 'james-wilson',
    name: 'James Wilson',
    role: 'Teacher',
    country: 'United States',
    city: 'Denver',
    coordinates: [-104.9903, 39.7392],
    bio: 'James teaches outdoor yoga and mountain retreats in the Colorado Rockies, combining rigorous Ashtanga practice with the healing power of high-altitude nature immersion. He leads week-long backpacking and yoga expeditions each summer.',
    photo: 'https://randomuser.me/api/portraits/men/5.jpg',
    designations: ['E-RYT 200', 'YACEP'],
    teachingStyles: ['Ashtanga', 'Hatha', 'Pranayama'],
    specialties: ['Outdoor Yoga', 'Retreats', 'Nature Immersion'],
    credits: { CE: 150, Community: 65, Karma: 85, Practice: 1300 },
    social: { instagram: '@james.yoga.colorado' },
    memberSince: '2021',
  },
  {
    id: 'natalie-rivera',
    name: 'Natalie Rivera',
    role: 'Teacher',
    country: 'United States',
    city: 'Miami',
    coordinates: [-80.1918, 25.7617],
    bio: 'Natalie brings a Latin American flair to her Vinyasa and dance-inspired yoga classes in Miami. Bilingual in English and Spanish, she teaches a diverse Miami clientele and leads retreats to Cuba and Colombia.',
    photo: 'https://randomuser.me/api/portraits/women/6.jpg',
    designations: ['RYT 500', 'RPYT'],
    teachingStyles: ['Vinyasa', 'Prenatal Yoga', 'Dance Yoga'],
    specialties: ['Bilingual Teaching', 'Women\'s Health', 'Retreat Leading'],
    credits: { CE: 210, Community: 70, Karma: 95, Practice: 1500 },
    social: { instagram: '@natalie.yoga.miami', website: 'https://natalierivera.yoga' },
    memberSince: '2019',
  },
  {
    id: 'christopher-lee',
    name: 'Christopher Lee',
    role: 'Teacher',
    country: 'United States',
    city: 'Boston',
    coordinates: [-71.0589, 42.3601],
    bio: 'Christopher is a Harvard-trained clinical psychologist who also teaches Yoga Nidra and mindfulness-based yoga in the Boston area. He integrates evidence-based psychology with yogic practice for stress and anxiety management.',
    photo: 'https://randomuser.me/api/portraits/men/6.jpg',
    designations: ['E-RYT 500', 'YACEP'],
    teachingStyles: ['Yoga Nidra', 'Meditation', 'Yin'],
    specialties: ['Mental Health', 'Anxiety', 'Sleep Issues'],
    credits: { CE: 260, Community: 85, Karma: 110, Practice: 1700 },
    social: { website: 'https://mindfulyogaboston.com', instagram: '@chrislee.yoga.boston' },
    memberSince: '2019',
    featured: true,
  },
  {
    id: 'megan-obrien',
    name: 'Megan O\'Brien',
    role: 'Teacher',
    country: 'United States',
    city: 'Nashville',
    coordinates: [-86.7816, 36.1627],
    bio: 'Megan weaves sound healing, mantra, and Kundalini yoga into transformational classes at her Nashville studio. She also produces yoga music and leads kirtan evenings that draw large crowds from the local spiritual community.',
    photo: 'https://randomuser.me/api/portraits/women/7.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Kundalini', 'Sound Healing', 'Meditation'],
    specialties: ['Mantra', 'Kirtan', 'Sound Baths'],
    credits: { CE: 195, Community: 140, Karma: 120, Practice: 1350 },
    social: { instagram: '@megan.obrien.yoga', youtube: 'MeganOBrienYoga' },
    memberSince: '2020',
  },
  {
    id: 'samuel-thompson',
    name: 'Samuel Thompson',
    role: 'Teacher',
    country: 'United States',
    city: 'Atlanta',
    coordinates: [-84.3880, 33.7490],
    bio: 'Samuel teaches Iyengar Yoga with a focus on precision, alignment, and therapeutic application. Trained under certified Iyengar teachers in Pune and the United States, he works extensively with students managing scoliosis and chronic back pain.',
    photo: 'https://randomuser.me/api/portraits/men/7.jpg',
    designations: ['E-RYT 500'],
    teachingStyles: ['Iyengar', 'Therapeutic', 'Hatha'],
    specialties: ['Alignment', 'Back Pain', 'Props-Based Practice'],
    credits: { CE: 290, Community: 50, Karma: 75, Practice: 2200 },
    social: { website: 'https://iyengaratlanta.com', instagram: '@samuel.iyengar.atl' },
    memberSince: '2018',
  },
  {
    id: 'lauren-hayes',
    name: 'Lauren Hayes',
    role: 'Teacher',
    country: 'United States',
    city: 'Boulder',
    coordinates: [-105.2705, 40.0150],
    bio: 'Lauren is a Boulder-based Anusara teacher with a deep background in anatomy and movement science. She leads popular weekend workshops on backbends and arm balances for intermediate and advanced practitioners.',
    photo: 'https://randomuser.me/api/portraits/women/8.jpg',
    designations: ['E-RYT 500', 'YACEP'],
    teachingStyles: ['Anusara', 'Hatha', 'Vinyasa'],
    specialties: ['Arm Balances', 'Backbends', 'Anatomy'],
    credits: { CE: 230, Community: 70, Karma: 90, Practice: 1750 },
    social: { instagram: '@lauren.hayes.yoga', website: 'https://laurenhayesyoga.com' },
    memberSince: '2019',
    featured: true,
  },
  {
    id: 'aaron-mitchell',
    name: 'Aaron Mitchell',
    role: 'Teacher',
    country: 'United States',
    city: 'Phoenix',
    coordinates: [-112.0740, 33.4484],
    bio: 'Aaron offers early morning Ashtanga Mysore classes in Phoenix and has taught at studios across the American Southwest. His practice-first philosophy encourages students to develop self-reliance on the mat.',
    photo: 'https://randomuser.me/api/portraits/men/19.jpg',
    designations: ['E-RYT 200', 'YACEP'],
    teachingStyles: ['Ashtanga', 'Mysore Method', 'Pranayama'],
    specialties: ['Mysore Program', 'Self-Practice', 'Morning Yoga'],
    credits: { CE: 170, Community: 45, Karma: 80, Practice: 1450 },
    social: { instagram: '@aaronmitchell.yoga' },
    memberSince: '2021',
  },

  // Canada – 11 teachers
  {
    id: 'sophia-chen',
    name: 'Sophia Chen',
    role: 'Teacher',
    country: 'Canada',
    city: 'Toronto',
    coordinates: [-79.3832, 43.6532],
    bio: 'Sophia leads a busy yoga studio in Toronto\'s Kensington Market, offering Hatha, Yin, and Prenatal classes. She is also the founder of a charitable program that brings free yoga to newcomer women across the city.',
    photo: 'https://randomuser.me/api/portraits/women/9.jpg',
    designations: ['E-RYT 500', 'RPYT', 'YACEP'],
    teachingStyles: ['Hatha', 'Yin', 'Prenatal Yoga'],
    specialties: ['Prenatal', 'Community Programs', 'Newcomer Outreach'],
    credits: { CE: 240, Community: 200, Karma: 175, Practice: 1650 },
    social: { website: 'https://sophiayogatoonto.ca', instagram: '@sophia.chen.yoga' },
    memberSince: '2019',
    featured: true,
  },
  {
    id: 'ethan-murphy',
    name: 'Ethan Murphy',
    role: 'Teacher',
    country: 'Canada',
    city: 'Vancouver',
    coordinates: [-123.1216, 49.2827],
    bio: 'Ethan teaches Power Yoga and Aerial Yoga in Vancouver with a spirited, playful energy that keeps his classes consistently full. He has trained in Thailand, India, and the US, bringing an eclectic international flavour to his teaching.',
    photo: 'https://randomuser.me/api/portraits/men/8.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Power Yoga', 'Aerial Yoga', 'Vinyasa'],
    specialties: ['Aerial Silks', 'Inversion Work', 'Retreat Leading'],
    credits: { CE: 200, Community: 80, Karma: 110, Practice: 1550 },
    social: { instagram: '@ethan.murphy.yoga', youtube: 'EthanMurphyYoga' },
    memberSince: '2020',
  },
  {
    id: 'emma-tremblay',
    name: 'Emma Tremblay',
    role: 'Teacher',
    country: 'Canada',
    city: 'Montreal',
    coordinates: [-73.5673, 45.5017],
    bio: 'Emma teaches bilingual (French/English) Yin and Restorative yoga at a beloved Montreal studio in the Plateau neighbourhood. Her warmth and thorough anatomical cues make her classes a favourite for students with chronic pain.',
    photo: 'https://randomuser.me/api/portraits/women/10.jpg',
    designations: ['E-RYT 200', 'YACEP'],
    teachingStyles: ['Yin', 'Restorative', 'Meditation'],
    specialties: ['Chronic Pain', 'Bilingual Teaching', 'Connective Tissue'],
    credits: { CE: 180, Community: 95, Karma: 85, Practice: 1100 },
    social: { instagram: '@emma.tremblay.yoga', website: 'https://emmatremblay.ca' },
    memberSince: '2020',
  },
  {
    id: 'liam-patterson',
    name: 'Liam Patterson',
    role: 'Teacher',
    country: 'Canada',
    city: 'Calgary',
    coordinates: [-114.0719, 51.0447],
    bio: 'Liam teaches hot yoga and meditation in Calgary and is a certified Level 2 Reiki practitioner who integrates energy work into his cool-down and savasana practices. He leads popular men-only yoga workshops to destigmatise the practice.',
    photo: 'https://randomuser.me/api/portraits/men/9.jpg',
    designations: ['RYT 500'],
    teachingStyles: ['Hot Yoga', 'Meditation', 'Hatha'],
    specialties: ['Men\'s Yoga', 'Reiki', 'Energy Work'],
    credits: { CE: 165, Community: 75, Karma: 90, Practice: 1250 },
    social: { instagram: '@liam.patterson.yoga' },
    memberSince: '2021',
  },
  {
    id: 'isabelle-gagnon',
    name: 'Isabelle Gagnon',
    role: 'Teacher',
    country: 'Canada',
    city: 'Ottawa',
    coordinates: [-75.6972, 45.4215],
    bio: 'Isabelle is a well-respected Ottawa teacher specialising in therapeutic yoga for seniors and those with neurodegenerative conditions. She works closely with physiotherapists and neurologists to support patients through movement.',
    photo: 'https://randomuser.me/api/portraits/women/11.jpg',
    designations: ['E-RYT 500', 'YACEP', 'RCYT'],
    teachingStyles: ['Therapeutic', 'Gentle Yoga', 'Restorative'],
    specialties: ['Yoga for Seniors', 'Neurological Conditions', 'Adaptive Yoga'],
    credits: { CE: 320, Community: 150, Karma: 130, Practice: 1800 },
    social: { website: 'https://isabellegyoga.ca', instagram: '@isabelle.gagnon.yoga' },
    memberSince: '2018',
    featured: true,
  },
  {
    id: 'ryan-macdonald',
    name: 'Ryan MacDonald',
    role: 'Teacher',
    country: 'Canada',
    city: 'Edmonton',
    coordinates: [-113.4909, 53.5461],
    bio: 'Ryan is a former hockey player who discovered yoga after a knee injury ended his playing career. He now teaches athletic yoga in Edmonton with a focus on mobility, strength, and mental resilience for athletes and non-athletes alike.',
    photo: 'https://randomuser.me/api/portraits/men/10.jpg',
    designations: ['RYT 200', 'YACEP'],
    teachingStyles: ['Power Yoga', 'Hatha', 'Vinyasa'],
    specialties: ['Athletic Yoga', 'Mobility', 'Sports Recovery'],
    credits: { CE: 130, Community: 55, Karma: 70, Practice: 990 },
    social: { instagram: '@ryan.macdonald.yoga' },
    memberSince: '2022',
  },
  {
    id: 'clara-dubois',
    name: 'Clara Dubois',
    role: 'Teacher',
    country: 'Canada',
    city: 'Victoria',
    coordinates: [-123.3656, 48.4284],
    bio: 'Clara teaches gentle forest yoga and Yoga Nidra on Vancouver Island, incorporating the natural landscape into her sessions. She also runs a popular online programme for insomnia and anxiety that has attracted students from across Canada.',
    photo: 'https://randomuser.me/api/portraits/women/12.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Yoga Nidra', 'Gentle Yoga', 'Meditation'],
    specialties: ['Sleep & Insomnia', 'Anxiety', 'Nature Yoga'],
    credits: { CE: 210, Community: 100, Karma: 115, Practice: 1400 },
    social: { website: 'https://claraduboisyoga.ca', instagram: '@clara.dubois.yoga' },
    memberSince: '2020',
  },
  {
    id: 'noah-williams',
    name: 'Noah Williams',
    role: 'Teacher',
    country: 'Canada',
    city: 'Halifax',
    coordinates: [-63.5752, 44.6488],
    bio: 'Noah brings Ashtanga Vinyasa to the Atlantic coast with a rigorous morning Mysore programme in Halifax that has built a loyal local community. He travels to Mysore biannually to continue his own studies.',
    photo: 'https://randomuser.me/api/portraits/men/11.jpg',
    designations: ['E-RYT 500'],
    teachingStyles: ['Ashtanga', 'Mysore Method', 'Pranayama'],
    specialties: ['Primary Series', 'Intermediate Series', 'Adjustments'],
    credits: { CE: 260, Community: 60, Karma: 100, Practice: 2050 },
    social: { instagram: '@noah.williams.ashtanga' },
    memberSince: '2019',
  },
  {
    id: 'amelie-bergeron',
    name: 'Amélie Bergeron',
    role: 'Teacher',
    country: 'Canada',
    city: 'Quebec City',
    coordinates: [-71.2082, 46.8139],
    bio: 'Amélie teaches Hatha and kids yoga in Quebec City, running popular after-school yoga programmes in local elementary schools. She is one of the leading advocates for yoga in Quebec\'s public education system.',
    photo: 'https://randomuser.me/api/portraits/women/13.jpg',
    designations: ['RYT 200', 'RCYT', 'YACEP'],
    teachingStyles: ['Kids Yoga', 'Hatha', 'Gentle Yoga'],
    specialties: ['Children\'s Yoga', 'School Programmes', 'Family Yoga'],
    credits: { CE: 145, Community: 180, Karma: 100, Practice: 800 },
    social: { instagram: '@amelie.yoga.quebec' },
    memberSince: '2021',
  },
  {
    id: 'connor-fraser',
    name: 'Connor Fraser',
    role: 'Teacher',
    country: 'Canada',
    city: 'Kelowna',
    coordinates: [-119.4960, 49.8880],
    bio: 'Connor combines outdoor adventure and yoga at his Okanagan wellness centre, hosting paddleboard yoga on the lake and vineyard yoga at local wineries. His immersive experiences blend movement, nature, and community.',
    photo: 'https://randomuser.me/api/portraits/men/12.jpg',
    designations: ['RYT 200'],
    teachingStyles: ['Vinyasa', 'Hatha', 'Outdoor Yoga'],
    specialties: ['SUP Yoga', 'Retreat Facilitation', 'Experiential Yoga'],
    credits: { CE: 110, Community: 85, Karma: 60, Practice: 870 },
    social: { instagram: '@connor.fraser.yoga', website: 'https://okanaganflow.ca' },
    memberSince: '2022',
  },
  {
    id: 'zoe-taylor',
    name: 'Zoe Taylor',
    role: 'Teacher',
    country: 'Canada',
    city: 'Hamilton',
    coordinates: [-79.8711, 43.2557],
    bio: 'Zoe is a Bikram-trained teacher now running her own hot studio in Hamilton with a more inclusive, trauma-informed approach to heat practice. She mentors new yoga teachers through a local teacher training assistant programme.',
    photo: 'https://randomuser.me/api/portraits/women/14.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Hot Yoga', 'Bikram', 'Trauma-Sensitive Yoga'],
    specialties: ['Heat Practice', 'Teacher Mentoring', 'Studio Operations'],
    credits: { CE: 220, Community: 90, Karma: 105, Practice: 1600 },
    social: { instagram: '@zoe.taylor.hotyoga' },
    memberSince: '2019',
  },

  // United Kingdom – 5 teachers
  {
    id: 'charlotte-davies',
    name: 'Charlotte Davies',
    role: 'Teacher',
    country: 'United Kingdom',
    city: 'London',
    coordinates: [-0.1276, 51.5074],
    bio: 'Charlotte is a senior yoga teacher and teacher trainer based in Notting Hill, London, with twenty years of practice in the Scaravelli tradition. She leads mentorship programmes for early-career yoga teachers across the UK and Europe.',
    photo: 'https://randomuser.me/api/portraits/women/15.jpg',
    designations: ['E-RYT 500', 'YACEP'],
    teachingStyles: ['Scaravelli Yoga', 'Hatha', 'Meditation'],
    specialties: ['Teacher Mentoring', 'Advanced Methodology', 'Philosophy'],
    credits: { CE: 380, Community: 120, Karma: 200, Practice: 3000 },
    social: { website: 'https://charlottedaviesyoga.co.uk', instagram: '@charlotte.davies.yoga' },
    memberSince: '2017',
    featured: true,
  },
  {
    id: 'james-harrison',
    name: 'James Harrison',
    role: 'Teacher',
    country: 'United Kingdom',
    city: 'Edinburgh',
    coordinates: [-3.1883, 55.9533],
    bio: 'James teaches Iyengar yoga and meditation in Edinburgh with methodical precision and warmth. He studied for four years at the Ramamani Iyengar Memorial Yoga Institute in Pune and continues to deepen his practice each year.',
    photo: 'https://randomuser.me/api/portraits/men/13.jpg',
    designations: ['E-RYT 500'],
    teachingStyles: ['Iyengar', 'Hatha', 'Pranayama'],
    specialties: ['Props', 'Alignment', 'Advanced Pranayama'],
    credits: { CE: 310, Community: 80, Karma: 150, Practice: 2500 },
    social: { instagram: '@james.harrison.iyengar' },
    memberSince: '2018',
  },
  {
    id: 'hannah-clarke',
    name: 'Hannah Clarke',
    role: 'Teacher',
    country: 'United Kingdom',
    city: 'Manchester',
    coordinates: [-2.2426, 53.4808],
    bio: 'Hannah\'s accessible Hatha classes have built a thriving community at her Manchester co-operative studio. She is a certified mental health first aider who brings trauma-informed principles to every class she teaches.',
    photo: 'https://randomuser.me/api/portraits/women/16.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Hatha', 'Trauma-Sensitive Yoga', 'Gentle Yoga'],
    specialties: ['Mental Health', 'Accessibility', 'Community Yoga'],
    credits: { CE: 190, Community: 160, Karma: 140, Practice: 1200 },
    social: { instagram: '@hannah.clarke.yoga', website: 'https://manchesteryogacoop.co.uk' },
    memberSince: '2019',
  },
  {
    id: 'oliver-bennett',
    name: 'Oliver Bennett',
    role: 'Teacher',
    country: 'United Kingdom',
    city: 'Bristol',
    coordinates: [-2.5879, 51.4545],
    bio: 'Oliver teaches Vinyasa and Acro Yoga in Bristol and runs an annual summer festival on the Clifton Downs. His high-energy, music-infused classes are a hallmark of Bristol\'s thriving yoga scene.',
    photo: 'https://randomuser.me/api/portraits/men/14.jpg',
    designations: ['RYT 500'],
    teachingStyles: ['Vinyasa', 'Acro Yoga', 'Power Yoga'],
    specialties: ['Acrobatics', 'Festivals', 'Partner Yoga'],
    credits: { CE: 175, Community: 110, Karma: 95, Practice: 1350 },
    social: { instagram: '@oliver.bennett.yoga', youtube: 'OliverBennettYoga' },
    memberSince: '2020',
  },
  {
    id: 'imogen-fletcher',
    name: 'Imogen Fletcher',
    role: 'Teacher',
    country: 'United Kingdom',
    city: 'Brighton',
    coordinates: [-0.1378, 50.8225],
    bio: 'Imogen leads Yin Yoga and Women\'s Wellness workshops from her sun-filled Brighton studio, specialising in yoga for hormonal health and the menstrual cycle. She is the author of a popular e-book on yoga and perimenopause.',
    photo: 'https://randomuser.me/api/portraits/women/17.jpg',
    designations: ['E-RYT 200', 'RPYT'],
    teachingStyles: ['Yin', 'Restorative', 'Prenatal Yoga'],
    specialties: ['Women\'s Health', 'Hormonal Yoga', 'Perimenopause'],
    credits: { CE: 200, Community: 90, Karma: 105, Practice: 1450 },
    social: { instagram: '@imogen.yoga.brighton', website: 'https://imogenyoga.co.uk' },
    memberSince: '2019',
  },

  // Australia – 3 teachers
  {
    id: 'chloe-anderson',
    name: 'Chloe Anderson',
    role: 'Teacher',
    country: 'Australia',
    city: 'Sydney',
    coordinates: [151.2093, -33.8688],
    bio: 'Chloe teaches Vinyasa and beach yoga at a Bondi studio and is known for making advanced postures approachable for everyday practitioners. She leads yoga surf retreats in Bali and along the New South Wales coast each year.',
    photo: 'https://randomuser.me/api/portraits/women/18.jpg',
    designations: ['E-RYT 200', 'YACEP'],
    teachingStyles: ['Vinyasa', 'Outdoor Yoga', 'Power Yoga'],
    specialties: ['Beach Yoga', 'Surf Retreats', 'Advanced Asana'],
    credits: { CE: 170, Community: 75, Karma: 90, Practice: 1250 },
    social: { instagram: '@chloe.yoga.bondi', website: 'https://chloeyogasydney.com.au' },
    memberSince: '2021',
  },
  {
    id: 'jake-morrison',
    name: 'Jake Morrison',
    role: 'Teacher',
    country: 'Australia',
    city: 'Melbourne',
    coordinates: [144.9631, -37.8136],
    bio: 'Jake is a meditation teacher and yoga guide working in Melbourne\'s inner suburbs, blending Vipassana meditation with Hatha yoga in his signature stillness-focused classes. He has studied at centres in India, Burma, and Thailand.',
    photo: 'https://randomuser.me/api/portraits/men/15.jpg',
    designations: ['E-RYT 500'],
    teachingStyles: ['Hatha', 'Meditation', 'Yoga Nidra'],
    specialties: ['Vipassana', 'Long Meditation Sits', 'Retreat Facilitation'],
    credits: { CE: 290, Community: 100, Karma: 170, Practice: 2300 },
    social: { instagram: '@jake.morrison.meditation' },
    memberSince: '2018',
    featured: true,
  },
  {
    id: 'sienna-walsh',
    name: 'Sienna Walsh',
    role: 'Teacher',
    country: 'Australia',
    city: 'Brisbane',
    coordinates: [153.0251, -27.4698],
    bio: 'Sienna runs a family yoga and kids wellness studio in Brisbane, offering parent-and-baby yoga, kids classes, and teen mindfulness programmes. Her inclusive space is a beloved community hub for young families across Queensland.',
    photo: 'https://randomuser.me/api/portraits/women/19.jpg',
    designations: ['RYT 200', 'RCYT', 'RPYT'],
    teachingStyles: ['Kids Yoga', 'Prenatal Yoga', 'Gentle Yoga'],
    specialties: ['Babies & Toddlers', 'Teen Yoga', 'Family Wellness'],
    credits: { CE: 140, Community: 160, Karma: 95, Practice: 850 },
    social: { instagram: '@sienna.family.yoga' },
    memberSince: '2021',
  },

  // Germany – 3 teachers
  {
    id: 'lena-mueller',
    name: 'Lena Müller',
    role: 'Teacher',
    country: 'Germany',
    city: 'Berlin',
    coordinates: [13.4050, 52.5200],
    bio: 'Lena is a Berlin-based Jivamukti teacher who incorporates activism and ahimsa (non-harming) philosophy into every class she teaches. She runs free yoga classes for asylum seekers and organises an annual yoga-for-climate event.',
    photo: 'https://randomuser.me/api/portraits/women/20.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Jivamukti', 'Vinyasa', 'Meditation'],
    specialties: ['Vegan Lifestyle', 'Activism', 'Philosophy'],
    credits: { CE: 210, Community: 220, Karma: 180, Practice: 1400 },
    social: { instagram: '@lena.yoga.berlin', website: 'https://lenayoga.de' },
    memberSince: '2019',
  },
  {
    id: 'max-schneider',
    name: 'Max Schneider',
    role: 'Teacher',
    country: 'Germany',
    city: 'Munich',
    coordinates: [11.5820, 48.1351],
    bio: 'Max teaches athletic Vinyasa and functional movement yoga at a popular Munich studio. An ex-professional triathlete, he integrates sport science principles into yoga sequencing for peak performance and longevity.',
    photo: 'https://randomuser.me/api/portraits/men/16.jpg',
    designations: ['RYT 500'],
    teachingStyles: ['Vinyasa', 'Power Yoga', 'Hatha'],
    specialties: ['Endurance Athletes', 'Functional Movement', 'Performance'],
    credits: { CE: 185, Community: 55, Karma: 80, Practice: 1500 },
    social: { instagram: '@max.schneider.yoga', youtube: 'MaxSchneiderYoga' },
    memberSince: '2020',
  },
  {
    id: 'julia-weber',
    name: 'Julia Weber',
    role: 'Teacher',
    country: 'Germany',
    city: 'Hamburg',
    coordinates: [9.9937, 53.5511],
    bio: 'Julia teaches Restorative and Yoga Nidra in Hamburg with a clinical background in psychotherapy. Her Saturday deep-rest workshops regularly sell out months in advance, attracting practitioners from across northern Germany.',
    photo: 'https://randomuser.me/api/portraits/women/21.jpg',
    designations: ['E-RYT 200', 'YACEP'],
    teachingStyles: ['Yoga Nidra', 'Restorative', 'Yin'],
    specialties: ['Deep Rest', 'Nervous System', 'Psychotherapy Integration'],
    credits: { CE: 195, Community: 80, Karma: 95, Practice: 1100 },
    social: { instagram: '@julia.weber.yoga', website: 'https://juliayoga.de' },
    memberSince: '2020',
  },

  // India – 2 teachers
  {
    id: 'ravi-krishnan',
    name: 'Ravi Krishnan',
    role: 'Teacher',
    country: 'India',
    city: 'Bangalore',
    coordinates: [77.5946, 12.9716],
    bio: 'Ravi is a classical Hatha and Sanskrit scholar teaching in Bangalore, with an unbroken lineage of practice stretching back four generations. He offers rare Vedic chanting courses alongside his asana and pranayama classes.',
    photo: 'https://randomuser.me/api/portraits/men/17.jpg',
    designations: ['E-RYT 500', 'YACEP'],
    teachingStyles: ['Hatha', 'Pranayama', 'Vedic Chanting'],
    specialties: ['Sanskrit', 'Classical Yoga', 'Lineage-Based Teaching'],
    credits: { CE: 400, Community: 150, Karma: 300, Practice: 4000 },
    social: { website: 'https://raviyoga.in', instagram: '@ravi.krishnan.yoga' },
    memberSince: '2017',
    featured: true,
  },
  {
    id: 'deepa-nair',
    name: 'Deepa Nair',
    role: 'Teacher',
    country: 'India',
    city: 'Mumbai',
    coordinates: [72.8777, 19.0760],
    bio: 'Deepa leads sought-after Ashtanga and Vinyasa teacher trainings from her Mumbai studio, having personally graduated over 400 teachers. She is a vocal advocate for ethical yoga teaching standards in India and globally.',
    photo: 'https://randomuser.me/api/portraits/women/22.jpg',
    designations: ['E-RYT 500', 'YACEP', 'RYS 200'],
    teachingStyles: ['Ashtanga', 'Vinyasa', 'Pranayama'],
    specialties: ['Teacher Training', 'Ethics', 'Advanced Practice'],
    credits: { CE: 350, Community: 200, Karma: 250, Practice: 3500 },
    social: { instagram: '@deepa.nair.yoga', website: 'https://deepanairyoga.com' },
    memberSince: '2017',
    featured: true,
  },

  // Italy – 1 teacher
  {
    id: 'giulia-romano',
    name: 'Giulia Romano',
    role: 'Teacher',
    country: 'Italy',
    city: 'Rome',
    coordinates: [12.4964, 41.9028],
    bio: 'Giulia teaches Hatha and philosophy-inspired yoga near the Borghese gardens in Rome. Her Sunday philosophy sessions exploring the Yoga Sutras of Patanjali draw scholars, artists, and practitioners together in rich conversation.',
    photo: 'https://randomuser.me/api/portraits/women/23.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Hatha', 'Yoga Philosophy', 'Meditation'],
    specialties: ['Yoga Sutras', 'Philosophy', 'Classical Texts'],
    credits: { CE: 220, Community: 95, Karma: 120, Practice: 1600 },
    social: { instagram: '@giulia.yoga.roma', website: 'https://giuliaromano.it' },
    memberSince: '2020',
  },

  // Netherlands – 1 teacher
  {
    id: 'lars-van-dijk',
    name: 'Lars van Dijk',
    role: 'Teacher',
    country: 'Netherlands',
    city: 'Amsterdam',
    coordinates: [4.9041, 52.3676],
    bio: 'Lars blends Ashtanga and somatic movement in his Amsterdam studio and teaches internationally at festivals including Wanderlust and BaliSpirit. His methodical yet playful teaching style has made him one of the Netherlands\' most recognised yoga voices.',
    photo: 'https://randomuser.me/api/portraits/men/18.jpg',
    designations: ['E-RYT 500', 'YACEP'],
    teachingStyles: ['Ashtanga', 'Somatic Movement', 'Vinyasa'],
    specialties: ['Festivals', 'International Retreats', 'Somatic Practices'],
    credits: { CE: 270, Community: 100, Karma: 140, Practice: 2100 },
    social: { instagram: '@lars.vandijk.yoga', website: 'https://larsvandijk.nl' },
    memberSince: '2019',
  },

  // Ireland – 1 teacher
  {
    id: 'siobhan-murphy',
    name: 'Siobhán Murphy',
    role: 'Teacher',
    country: 'Ireland',
    city: 'Dublin',
    coordinates: [-6.2603, 53.3498],
    bio: 'Siobhán has been a cornerstone of Dublin\'s yoga community for over a decade, teaching Iyengar and gentle yoga at her Ranelagh studio. She trained in Pune and brings a warmth and rigour to her classes that inspires deep loyalty among her students.',
    photo: 'https://randomuser.me/api/portraits/women/24.jpg',
    designations: ['E-RYT 500'],
    teachingStyles: ['Iyengar', 'Gentle Yoga', 'Hatha'],
    specialties: ['Props', 'Older Adults', 'Long-Term Practitioners'],
    credits: { CE: 290, Community: 85, Karma: 130, Practice: 2400 },
    social: { website: 'https://siobhanyoga.ie', instagram: '@siobhan.murphy.yoga' },
    memberSince: '2018',
  },

  // France – 1 teacher
  {
    id: 'camille-moreau',
    name: 'Camille Moreau',
    role: 'Teacher',
    country: 'France',
    city: 'Paris',
    coordinates: [2.3522, 48.8566],
    bio: 'Camille teaches dynamic Vinyasa and Yin Yoga in the Marais district of Paris, weaving philosophy and poetry into her sequences. She leads an acclaimed annual retreat to the south of France that blends yoga, cuisine, and slow travel.',
    photo: 'https://randomuser.me/api/portraits/women/25.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Vinyasa', 'Yin', 'Meditation'],
    specialties: ['Retreats', 'Lifestyle Yoga', 'Philosophy'],
    credits: { CE: 205, Community: 70, Karma: 100, Practice: 1450 },
    social: { instagram: '@camille.yoga.paris', website: 'https://camillemoreauyoga.fr' },
    memberSince: '2020',
  },

  // South Africa – 1 teacher
  {
    id: 'naledi-dlamini',
    name: 'Naledi Dlamini',
    role: 'Teacher',
    country: 'South Africa',
    city: 'Cape Town',
    coordinates: [18.4241, -33.9249],
    bio: 'Naledi brings traditional Ubuntu philosophy to her yoga teaching in Cape Town, creating deeply communal practice spaces where connection and belonging come first. She runs free yoga programmes in the Cape Flats and trains teachers in social-justice yoga.',
    photo: 'https://randomuser.me/api/portraits/women/26.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Hatha', 'Trauma-Sensitive Yoga', 'Meditation'],
    specialties: ['Social Justice Yoga', 'Community Healing', 'Ubuntu Philosophy'],
    credits: { CE: 180, Community: 280, Karma: 220, Practice: 1100 },
    social: { instagram: '@naledi.yoga.cpt', website: 'https://nalediyoga.co.za' },
    memberSince: '2020',
  },

  // ── STUDENTS (28) ────────────────────────────────────────────────────────────

  // United States – 8 students
  {
    id: 'tyler-nguyen',
    name: 'Tyler Nguyen',
    role: 'Student',
    country: 'United States',
    city: 'New York',
    coordinates: [-74.0060, 40.7128],
    bio: 'Tyler is a graphic designer in Brooklyn who discovered yoga through a corporate wellness programme and has not looked back. He practices Vinyasa three times a week and is saving to attend a 200-hour training in Costa Rica.',
    photo: 'https://randomuser.me/api/portraits/men/20.jpg',
    designations: [],
    teachingStyles: ['Vinyasa', 'Hatha'],
    specialties: [],
    credits: { CE: 30, Community: 15, Karma: 20, Practice: 310 },
    social: { instagram: '@tyler.nguyen.yoga' },
    memberSince: '2023',
  },
  {
    id: 'madison-clark',
    name: 'Madison Clark',
    role: 'Student',
    country: 'United States',
    city: 'Los Angeles',
    coordinates: [-118.2437, 34.0522],
    bio: 'Madison is a film student at UCLA who practices yoga as a daily grounding ritual amidst the chaos of production schedules. She is particularly drawn to Yin and meditation, and aspires to teach retreats for creative professionals.',
    photo: 'https://randomuser.me/api/portraits/women/28.jpg',
    designations: [],
    teachingStyles: ['Yin', 'Meditation'],
    specialties: [],
    credits: { CE: 25, Community: 10, Karma: 15, Practice: 250 },
    social: { instagram: '@madison.yoga.la' },
    memberSince: '2024',
  },
  {
    id: 'jordan-davis',
    name: 'Jordan Davis',
    role: 'Student',
    country: 'United States',
    city: 'Chicago',
    coordinates: [-87.6298, 41.8781],
    bio: 'Jordan is a nurse working night shifts in Chicago who relies on restorative yoga to decompress after demanding shifts. They are currently completing a 200-hour teacher training with the goal of introducing yoga into clinical settings.',
    photo: 'https://randomuser.me/api/portraits/men/21.jpg',
    designations: [],
    teachingStyles: ['Restorative', 'Yin'],
    specialties: ['Healthcare Workers', 'Burnout'],
    credits: { CE: 45, Community: 20, Karma: 30, Practice: 420 },
    social: {},
    memberSince: '2023',
  },
  {
    id: 'ava-robinson',
    name: 'Ava Robinson',
    role: 'Student',
    country: 'United States',
    city: 'San Diego',
    coordinates: [-117.1611, 32.7157],
    bio: 'Ava is a marine biologist in San Diego who practices yoga and freediving as complementary breath disciplines. Her pranayama curiosity has led her to explore Holotropic Breathwork and Wim Hof alongside her yoga studies.',
    photo: 'https://randomuser.me/api/portraits/women/29.jpg',
    designations: [],
    teachingStyles: ['Pranayama', 'Vinyasa'],
    specialties: ['Breathwork', 'Freediving Integration'],
    credits: { CE: 35, Community: 10, Karma: 25, Practice: 370 },
    social: { instagram: '@ava.yoga.sandiego' },
    memberSince: '2023',
  },
  {
    id: 'marcus-williams',
    name: 'Marcus Williams',
    role: 'Student',
    country: 'United States',
    city: 'Houston',
    coordinates: [-95.3698, 29.7604],
    bio: 'Marcus played college football at Texas A&M and found yoga during rehabilitation from a shoulder injury. He now practices Power Yoga and Hot Yoga regularly and actively encourages teammates and coaches to try the mat.',
    photo: 'https://randomuser.me/api/portraits/men/22.jpg',
    designations: [],
    teachingStyles: ['Power Yoga', 'Hot Yoga'],
    specialties: ['Athletes', 'Injury Recovery'],
    credits: { CE: 20, Community: 8, Karma: 12, Practice: 220 },
    social: { instagram: '@marcus.yoga.houston' },
    memberSince: '2024',
  },
  {
    id: 'caitlin-foster',
    name: 'Caitlin Foster',
    role: 'Student',
    country: 'United States',
    city: 'Philadelphia',
    coordinates: [-75.1652, 39.9526],
    bio: 'Caitlin is an elementary school teacher in Philadelphia who practices Hatha yoga every morning before work. She has completed her 200-hour training and is now deciding between teaching privately or opening a community studio.',
    photo: 'https://randomuser.me/api/portraits/women/30.jpg',
    designations: ['RYT 200'],
    teachingStyles: ['Hatha', 'Kids Yoga'],
    specialties: ['Education', 'Classroom Mindfulness'],
    credits: { CE: 55, Community: 35, Karma: 40, Practice: 520 },
    social: {},
    memberSince: '2022',
  },
  {
    id: 'dylan-carter',
    name: 'Dylan Carter',
    role: 'Student',
    country: 'United States',
    city: 'Austin',
    coordinates: [-97.7431, 30.2672],
    bio: 'Dylan is a musician and sound healer in Austin who is currently immersed in Kundalini yoga teacher training. He aims to combine live music, overtone singing, and yoga in immersive wellness experiences.',
    photo: 'https://randomuser.me/api/portraits/men/23.jpg',
    designations: [],
    teachingStyles: ['Kundalini', 'Sound Healing'],
    specialties: ['Music', 'Sound Baths'],
    credits: { CE: 40, Community: 30, Karma: 35, Practice: 380 },
    social: { instagram: '@dylan.sound.yoga' },
    memberSince: '2023',
  },
  {
    id: 'brianna-scott',
    name: 'Brianna Scott',
    role: 'Student',
    country: 'United States',
    city: 'Seattle',
    coordinates: [-122.3321, 47.6062],
    bio: 'Brianna is a software developer at a Seattle startup who uses yoga and meditation to manage the stress of an intense work environment. She blogs about the intersection of tech culture and mindfulness with a growing readership.',
    photo: 'https://randomuser.me/api/portraits/women/31.jpg',
    designations: [],
    teachingStyles: ['Meditation', 'Yin', 'Vinyasa'],
    specialties: ['Mindfulness Tech', 'Workplace Wellbeing'],
    credits: { CE: 30, Community: 15, Karma: 20, Practice: 290 },
    social: { instagram: '@brianna.yoga.seattle' },
    memberSince: '2023',
  },

  // Canada – 6 students
  {
    id: 'aiden-macpherson',
    name: 'Aiden MacPherson',
    role: 'Student',
    country: 'Canada',
    city: 'Toronto',
    coordinates: [-79.3832, 43.6532],
    bio: 'Aiden is a social work student in Toronto who began practicing yoga as part of his own mental health journey. He volunteers at a community yoga programme for youth in care and plans to pursue yoga teacher training after graduating.',
    photo: 'https://randomuser.me/api/portraits/men/24.jpg',
    designations: [],
    teachingStyles: ['Hatha', 'Meditation'],
    specialties: ['Youth Work', 'Mental Health'],
    credits: { CE: 20, Community: 45, Karma: 30, Practice: 200 },
    social: {},
    memberSince: '2023',
  },
  {
    id: 'lily-chen',
    name: 'Lily Chen',
    role: 'Student',
    country: 'Canada',
    city: 'Vancouver',
    coordinates: [-123.1216, 49.2827],
    bio: 'Lily is an acupuncturist in training in Vancouver who weaves together Traditional Chinese Medicine and yoga philosophy in her personal practice. She practices Yin Yoga to complement her clinical studies in meridian theory.',
    photo: 'https://randomuser.me/api/portraits/women/32.jpg',
    designations: [],
    teachingStyles: ['Yin', 'Restorative'],
    specialties: ['TCM', 'Meridian Yoga'],
    credits: { CE: 35, Community: 20, Karma: 25, Practice: 320 },
    social: { instagram: '@lily.yin.van' },
    memberSince: '2022',
  },
  {
    id: 'mathieu-cote',
    name: 'Mathieu Côté',
    role: 'Student',
    country: 'Canada',
    city: 'Montreal',
    coordinates: [-73.5673, 45.5017],
    bio: 'Mathieu is a visual artist in Montreal whose work is deeply informed by his Ashtanga practice. He photographs yoga practitioners for exhibitions exploring the intersection of devotion, discipline, and the human form.',
    photo: 'https://randomuser.me/api/portraits/men/25.jpg',
    designations: [],
    teachingStyles: ['Ashtanga', 'Hatha'],
    specialties: ['Yoga Photography', 'Arts Integration'],
    credits: { CE: 30, Community: 25, Karma: 20, Practice: 350 },
    social: { instagram: '@mathieu.yoga.mtl' },
    memberSince: '2022',
  },
  {
    id: 'paige-stewart',
    name: 'Paige Stewart',
    role: 'Student',
    country: 'Canada',
    city: 'Calgary',
    coordinates: [-114.0719, 51.0447],
    bio: 'Paige is a physiotherapist in Calgary who recently began practising yoga to better understand the movement system she works with clinically. She is completing a yin teacher training to broaden her therapeutic toolkit.',
    photo: 'https://randomuser.me/api/portraits/women/33.jpg',
    designations: [],
    teachingStyles: ['Yin', 'Therapeutic'],
    specialties: ['Physiotherapy', 'Clinical Movement'],
    credits: { CE: 45, Community: 15, Karma: 20, Practice: 390 },
    social: {},
    memberSince: '2023',
  },
  {
    id: 'owen-murphy',
    name: 'Owen Murphy',
    role: 'Student',
    country: 'Canada',
    city: 'Ottawa',
    coordinates: [-75.6972, 45.4215],
    bio: 'Owen is a policy analyst with the Canadian government who uses morning meditation and yoga as anchors in a demanding schedule. He is drawn to classical Hatha and spends weekends at a local retreat centre studying Vedanta.',
    photo: 'https://randomuser.me/api/portraits/men/26.jpg',
    designations: [],
    teachingStyles: ['Hatha', 'Meditation'],
    specialties: ['Vedanta', 'Classical Texts'],
    credits: { CE: 25, Community: 10, Karma: 15, Practice: 280 },
    social: {},
    memberSince: '2023',
  },
  {
    id: 'jade-beaumont',
    name: 'Jade Beaumont',
    role: 'Student',
    country: 'Canada',
    city: 'Victoria',
    coordinates: [-123.3656, 48.4284],
    bio: 'Jade is a former competitive swimmer now studying yoga therapy on Vancouver Island. She is particularly interested in breathwork and the nervous system, and is pursuing certification in Integrative Yoga Therapy.',
    photo: 'https://randomuser.me/api/portraits/women/34.jpg',
    designations: [],
    teachingStyles: ['Pranayama', 'Restorative'],
    specialties: ['Breathwork', 'Nervous System'],
    credits: { CE: 50, Community: 20, Karma: 30, Practice: 450 },
    social: { instagram: '@jade.yoga.victoria' },
    memberSince: '2022',
  },

  // United Kingdom – 3 students
  {
    id: 'jack-williams',
    name: 'Jack Williams',
    role: 'Student',
    country: 'United Kingdom',
    city: 'London',
    coordinates: [-0.1276, 51.5074],
    bio: 'Jack is a junior doctor in London who turned to yoga during his first hospital rotation and has not missed a week since. He practices early mornings at a Hackney studio and is considering specialising in integrative medicine.',
    photo: 'https://randomuser.me/api/portraits/men/27.jpg',
    designations: [],
    teachingStyles: ['Vinyasa', 'Meditation'],
    specialties: ['Healthcare Integration', 'Stress Management'],
    credits: { CE: 25, Community: 10, Karma: 15, Practice: 260 },
    social: {},
    memberSince: '2024',
  },
  {
    id: 'emily-watson',
    name: 'Emily Watson',
    role: 'Student',
    country: 'United Kingdom',
    city: 'Oxford',
    coordinates: [-1.2577, 51.7520],
    bio: 'Emily is reading Philosophy and Theology at Oxford and has been deepening her meditation and yoga practice alongside her academic studies. She leads a student yoga society and recently hosted a three-day mindfulness retreat at the university.',
    photo: 'https://randomuser.me/api/portraits/women/35.jpg',
    designations: [],
    teachingStyles: ['Meditation', 'Hatha'],
    specialties: ['Philosophy of Mind', 'Student Wellbeing'],
    credits: { CE: 30, Community: 40, Karma: 25, Practice: 290 },
    social: { instagram: '@emily.watson.yoga' },
    memberSince: '2023',
  },
  {
    id: 'harry-evans',
    name: 'Harry Evans',
    role: 'Student',
    country: 'United Kingdom',
    city: 'Leeds',
    coordinates: [-1.5491, 53.8008],
    bio: 'Harry is a personal trainer in Leeds who integrated yoga into his coaching after struggling with burnout. He now incorporates Yin and Restorative classes into his client programmes and is studying to become a yoga therapist.',
    photo: 'https://randomuser.me/api/portraits/men/28.jpg',
    designations: [],
    teachingStyles: ['Yin', 'Restorative', 'Power Yoga'],
    specialties: ['Personal Training Integration', 'Burnout'],
    credits: { CE: 40, Community: 20, Karma: 25, Practice: 380 },
    social: { instagram: '@harry.yoga.leeds' },
    memberSince: '2022',
  },

  // Australia – 2 students
  {
    id: 'sophie-turner',
    name: 'Sophie Turner',
    role: 'Student',
    country: 'Australia',
    city: 'Sydney',
    coordinates: [151.2093, -33.8688],
    bio: 'Sophie is a high school art teacher in Sydney who was introduced to yoga by her students during a mindfulness programme. She now maintains a daily practice and is completing a 300-hour advanced teacher training on weekends.',
    photo: 'https://randomuser.me/api/portraits/women/36.jpg',
    designations: ['RYT 200'],
    teachingStyles: ['Hatha', 'Vinyasa'],
    specialties: ['Arts', 'Teenage Yoga'],
    credits: { CE: 55, Community: 30, Karma: 35, Practice: 490 },
    social: { instagram: '@sophie.yoga.sydney' },
    memberSince: '2022',
  },
  {
    id: 'lachlan-brown',
    name: 'Lachlan Brown',
    role: 'Student',
    country: 'Australia',
    city: 'Perth',
    coordinates: [115.8605, -31.9505],
    bio: 'Lachlan is a FIFO (fly-in fly-out) miner in Western Australia who discovered meditation during a long stint at a remote site. He now practices yoga during his off-rotations in Perth and finds it essential for re-calibrating after weeks underground.',
    photo: 'https://randomuser.me/api/portraits/men/29.jpg',
    designations: [],
    teachingStyles: ['Meditation', 'Hatha'],
    specialties: ['Remote Workers', 'Reintegration'],
    credits: { CE: 15, Community: 10, Karma: 12, Practice: 180 },
    social: {},
    memberSince: '2024',
  },

  // Germany – 2 students
  {
    id: 'klara-schmidt',
    name: 'Klara Schmidt',
    role: 'Student',
    country: 'Germany',
    city: 'Berlin',
    coordinates: [13.4050, 52.5200],
    bio: 'Klara is a dance choreographer in Berlin who practices Somatic Movement and Yin Yoga to support her physical artistry and manage performance anxiety. She is writing a thesis on the relationship between contemporary dance and yogic embodiment.',
    photo: 'https://randomuser.me/api/portraits/women/37.jpg',
    designations: [],
    teachingStyles: ['Somatic Movement', 'Yin'],
    specialties: ['Dance', 'Embodiment', 'Performance Arts'],
    credits: { CE: 30, Community: 20, Karma: 18, Practice: 320 },
    social: { instagram: '@klara.dance.yoga' },
    memberSince: '2023',
  },
  {
    id: 'felix-richter',
    name: 'Felix Richter',
    role: 'Student',
    country: 'Germany',
    city: 'Frankfurt',
    coordinates: [8.6821, 50.1109],
    bio: 'Felix is an investment banker in Frankfurt who practices Ashtanga at 5:30 AM as a non-negotiable start to his day. He attributes his mental clarity and resilience to a rigorous yoga practice that keeps him grounded in a high-pressure environment.',
    photo: 'https://randomuser.me/api/portraits/men/30.jpg',
    designations: [],
    teachingStyles: ['Ashtanga', 'Meditation'],
    specialties: ['Finance Professionals', 'Stress Management'],
    credits: { CE: 20, Community: 8, Karma: 10, Practice: 240 },
    social: {},
    memberSince: '2023',
  },

  // Italy – 2 students
  {
    id: 'marco-rossi',
    name: 'Marco Rossi',
    role: 'Student',
    country: 'Italy',
    city: 'Florence',
    coordinates: [11.2558, 43.7696],
    bio: 'Marco is an architect in Florence who found yoga after a difficult period and has been a devoted practitioner for four years. He practices Vinyasa and Ashtanga daily and is planning to enrol in a 200-hour teacher training programme next year.',
    photo: 'https://randomuser.me/api/portraits/men/31.jpg',
    designations: [],
    teachingStyles: ['Vinyasa', 'Ashtanga'],
    specialties: [],
    credits: { CE: 40, Community: 22, Karma: 35, Practice: 480 },
    social: { instagram: '@marco.yoga.florence' },
    memberSince: '2022',
  },
  {
    id: 'valentina-esposito',
    name: 'Valentina Esposito',
    role: 'Student',
    country: 'Italy',
    city: 'Milan',
    coordinates: [9.1900, 45.4654],
    bio: 'Valentina is a fashion stylist in Milan whose yoga practice began as a recommendation from a physiotherapist for back pain. It quickly became a cornerstone of her life, leading her to study Yin Yoga and mindfulness at a centre in the Brera district.',
    photo: 'https://randomuser.me/api/portraits/women/38.jpg',
    designations: [],
    teachingStyles: ['Yin', 'Restorative'],
    specialties: ['Chronic Pain', 'Back Health'],
    credits: { CE: 30, Community: 12, Karma: 20, Practice: 310 },
    social: { instagram: '@valentina.yoga.milan' },
    memberSince: '2023',
  },

  // Netherlands – 2 students
  {
    id: 'daan-visser',
    name: 'Daan Visser',
    role: 'Student',
    country: 'Netherlands',
    city: 'Rotterdam',
    coordinates: [4.4777, 51.9244],
    bio: 'Daan is a harbour engineer in Rotterdam who uses yoga and meditation to decompress from complex project demands. He has been studying Zen meditation alongside Hatha yoga for three years and helps run his local sangha.',
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
    designations: [],
    teachingStyles: ['Hatha', 'Meditation'],
    specialties: ['Zen Practice', 'Engineering Professionals'],
    credits: { CE: 25, Community: 30, Karma: 20, Practice: 280 },
    social: {},
    memberSince: '2022',
  },
  {
    id: 'fleur-de-boer',
    name: 'Fleur de Boer',
    role: 'Student',
    country: 'Netherlands',
    city: 'Utrecht',
    coordinates: [5.1214, 52.0907],
    bio: 'Fleur is a midwife in Utrecht who recommends prenatal yoga to her clients and has immersed herself in RPYT training to deepen her understanding. She hopes to run yoga and birth preparation workshops at the birthing centre where she works.',
    photo: 'https://randomuser.me/api/portraits/women/39.jpg',
    designations: [],
    teachingStyles: ['Prenatal Yoga', 'Restorative'],
    specialties: ['Pregnancy', 'Birth Preparation'],
    credits: { CE: 50, Community: 25, Karma: 30, Practice: 430 },
    social: { instagram: '@fleur.yoga.utrecht' },
    memberSince: '2022',
  },

  // Ireland – 1 student
  {
    id: 'aoife-sullivan',
    name: 'Aoife Sullivan',
    role: 'Student',
    country: 'Ireland',
    city: 'Cork',
    coordinates: [-8.4756, 51.8985],
    bio: 'Aoife is a postgraduate researcher in Cork studying the neuroscience of contemplative practices. Her personal Hatha and meditation practice informs her academic work on the effects of mindfulness on the adolescent brain.',
    photo: 'https://randomuser.me/api/portraits/women/40.jpg',
    designations: [],
    teachingStyles: ['Hatha', 'Meditation'],
    specialties: ['Neuroscience', 'Adolescent Wellbeing'],
    credits: { CE: 35, Community: 20, Karma: 18, Practice: 350 },
    social: { instagram: '@aoife.yoga.cork' },
    memberSince: '2023',
  },

  // France – 1 student
  {
    id: 'hugo-leclerc',
    name: 'Hugo Leclerc',
    role: 'Student',
    country: 'France',
    city: 'Lyon',
    coordinates: [4.8357, 45.7640],
    bio: 'Hugo is a chef in Lyon who began practicing yoga after a mentor described it as the best thing he had ever done for his culinary creativity. He practices Hatha each morning before the restaurant opens and has started exploring pranayama deeply.',
    photo: 'https://randomuser.me/api/portraits/men/33.jpg',
    designations: [],
    teachingStyles: ['Hatha', 'Pranayama'],
    specialties: ['Creative Professionals', 'Morning Practice'],
    credits: { CE: 20, Community: 10, Karma: 12, Practice: 220 },
    social: {},
    memberSince: '2024',
  },

  // India – 1 student
  {
    id: 'arjun-patel',
    name: 'Arjun Patel',
    role: 'Student',
    country: 'India',
    city: 'Delhi',
    coordinates: [77.2090, 28.6139],
    bio: 'Arjun is an IT professional in Delhi who began practicing yoga to address posture problems from long hours at a desk. His interest deepened rapidly and he now studies classical yoga texts privately with a teacher in the Lodi Colony neighbourhood.',
    photo: 'https://randomuser.me/api/portraits/men/34.jpg',
    designations: [],
    teachingStyles: ['Hatha', 'Yoga Philosophy'],
    specialties: ['Classical Texts', 'Desk Worker Health'],
    credits: { CE: 25, Community: 12, Karma: 15, Practice: 270 },
    social: {},
    memberSince: '2023',
  },

  // ── WELLNESS PRACTITIONERS (5) ───────────────────────────────────────────────

  {
    id: 'diana-reeves',
    name: 'Diana Reeves',
    role: 'Wellness Practitioner',
    country: 'United States',
    city: 'Santa Fe',
    coordinates: [-105.9378, 35.6870],
    bio: 'Diana combines yoga, Ayurveda, and herbal medicine at her integrative wellness centre in Santa Fe. She has studied Ayurveda in Kerala and works with clients on seasonal cleanse programmes, yoga therapy, and personalised lifestyle medicine.',
    photo: 'https://randomuser.me/api/portraits/women/41.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Hatha', 'Restorative', 'Yoga Therapy'],
    specialties: ['Ayurveda', 'Herbal Medicine', 'Cleanse Programmes'],
    credits: { CE: 290, Community: 100, Karma: 160, Practice: 1800 },
    social: { website: 'https://dianareeves.com', instagram: '@diana.wellness.santafe' },
    memberSince: '2019',
    featured: true,
  },
  {
    id: 'kevin-park',
    name: 'Kevin Park',
    role: 'Wellness Practitioner',
    country: 'United States',
    city: 'Los Angeles',
    coordinates: [-118.2437, 34.0522],
    bio: 'Kevin is an integrative health coach and yoga guide working with high-performance professionals in Los Angeles. His programmes blend biohacking, nutrition, breathwork, and yoga to optimise cognitive and physical performance.',
    photo: 'https://randomuser.me/api/portraits/men/35.jpg',
    designations: ['RYT 200'],
    teachingStyles: ['Vinyasa', 'Pranayama', 'Meditation'],
    specialties: ['Biohacking', 'Executive Wellness', 'Performance Coaching'],
    credits: { CE: 150, Community: 60, Karma: 85, Practice: 1100 },
    social: { instagram: '@kevin.park.wellness', website: 'https://kevinparkhealth.com' },
    memberSince: '2021',
  },
  {
    id: 'madeleine-fortin',
    name: 'Madeleine Fortin',
    role: 'Wellness Practitioner',
    country: 'Canada',
    city: 'Montreal',
    coordinates: [-73.5673, 45.5017],
    bio: 'Madeleine is a naturopath and yoga therapist in Montreal who works at the intersection of natural medicine and movement therapy. She is known for her work with women experiencing fertility challenges, blending nutrition, herbs, and restorative yoga.',
    photo: 'https://randomuser.me/api/portraits/women/42.jpg',
    designations: ['RYT 500', 'RPYT'],
    teachingStyles: ['Restorative', 'Yoga Therapy', 'Yin'],
    specialties: ['Fertility', 'Women\'s Health', 'Naturopathy'],
    credits: { CE: 200, Community: 80, Karma: 110, Practice: 1200 },
    social: { website: 'https://madeleinefortin.ca', instagram: '@madeleine.wellness.mtl' },
    memberSince: '2020',
  },
  {
    id: 'niamh-oconnor',
    name: 'Niamh O\'Connor',
    role: 'Wellness Practitioner',
    country: 'United Kingdom',
    city: 'Birmingham',
    coordinates: [-1.8904, 52.4862],
    bio: 'Niamh works as an NHS-linked wellbeing practitioner in Birmingham, using yoga and mindfulness as therapeutic tools for patients with long-term conditions including fibromyalgia, MS, and chronic fatigue. Her research has been published in the British Journal of General Practice.',
    photo: 'https://randomuser.me/api/portraits/women/43.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Therapeutic', 'Yoga Nidra', 'Gentle Yoga'],
    specialties: ['Chronic Illness', 'NHS Integration', 'Clinical Yoga'],
    credits: { CE: 270, Community: 130, Karma: 140, Practice: 1500 },
    social: { website: 'https://niamhwellness.co.uk', instagram: '@niamh.yoga.bham' },
    memberSince: '2019',
    featured: true,
  },
  {
    id: 'anna-hoffmann',
    name: 'Anna Hoffmann',
    role: 'Wellness Practitioner',
    country: 'Germany',
    city: 'Cologne',
    coordinates: [6.9578, 50.9333],
    bio: 'Anna is a certified Yoga Therapist and somatic trauma specialist based in Cologne. She works with survivors of trauma in both individual and group settings, drawing on SE (Somatic Experiencing), EMDR, and trauma-informed yoga.',
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
    designations: ['RYT 500', 'YACEP'],
    teachingStyles: ['Trauma-Sensitive Yoga', 'Somatic Movement', 'Yoga Therapy'],
    specialties: ['Trauma Therapy', 'Somatic Experiencing', 'PTSD'],
    credits: { CE: 310, Community: 150, Karma: 170, Practice: 1700 },
    social: { website: 'https://annayogatherapie.de', instagram: '@anna.yoga.koeln' },
    memberSince: '2018',
  },

  // ── SCHOOLS (3) ──────────────────────────────────────────────────────────────

  {
    id: 'ananda-yoga-academy',
    name: 'Ananda Yoga Academy',
    role: 'School',
    country: 'India',
    city: 'Rishikesh',
    coordinates: [78.2676, 30.0869],
    bio: 'One of Rishikesh\'s most respected yoga schools, offering immersive 200- and 500-hour teacher trainings rooted in classical Hatha and Raja Yoga. With over 2,000 graduates worldwide, Ananda is committed to upholding the integrity of the yogic tradition.',
    photo: 'https://randomuser.me/api/portraits/men/36.jpg',
    designations: ['RYS 500', 'RYS 300', 'RYS 200'],
    teachingStyles: ['Hatha', 'Raja Yoga', 'Meditation'],
    specialties: ['Teacher Training', 'Ayurveda Integration', 'Sanskrit Studies'],
    credits: { CE: 0, Community: 500, Karma: 700, Practice: 0 },
    social: { website: 'https://anandayogaacademy.com', instagram: '@anandayoga.rishikesh', youtube: 'AnandaYogaAcademy' },
    memberSince: '2017',
    featured: true,
  },
  {
    id: 'gateway-yoga-school',
    name: 'Gateway Yoga School',
    role: 'School',
    country: 'United States',
    city: 'New York',
    coordinates: [-74.0060, 40.7128],
    bio: 'Gateway Yoga School is a GOYA-registered training school in the heart of Manhattan, known for its rigorous 300- and 500-hour advanced teacher training programmes. Faculty include senior teachers from Ashtanga, Iyengar, and Jivamukti lineages.',
    photo: 'https://randomuser.me/api/portraits/women/45.jpg',
    designations: ['RYS 500', 'RYS 300', 'YACEP'],
    teachingStyles: ['Ashtanga', 'Iyengar', 'Jivamukti'],
    specialties: ['Advanced Teacher Training', 'Multi-Style', 'Urban Yoga'],
    credits: { CE: 0, Community: 400, Karma: 550, Practice: 0 },
    social: { website: 'https://gatewayyoganyc.com', instagram: '@gateway.yoga.nyc' },
    memberSince: '2018',
    featured: true,
  },
  {
    id: 'north-shore-yoga-institute',
    name: 'North Shore Yoga Institute',
    role: 'School',
    country: 'Canada',
    city: 'Vancouver',
    coordinates: [-123.1216, 49.2827],
    bio: 'North Shore Yoga Institute offers 200-hour foundational and 300-hour advanced trainings from its North Vancouver campus, with a strong emphasis on trauma-informed and Indigenous-inclusive teaching methodologies. Scholarship places are offered each intake.',
    photo: 'https://randomuser.me/api/portraits/men/37.jpg',
    designations: ['RYS 200', 'RYS 300', 'YACEP'],
    teachingStyles: ['Hatha', 'Trauma-Sensitive Yoga', 'Inclusive Yoga'],
    specialties: ['Trauma-Informed Training', 'Indigenous Inclusion', 'Scholarships'],
    credits: { CE: 0, Community: 350, Karma: 400, Practice: 0 },
    social: { website: 'https://northshoreyoga.ca', instagram: '@northshore.yoga.institute' },
    memberSince: '2020',
  },
];

export const allCountries = ['All', ...Array.from(new Set(members.map(m => m.country))).sort()];
export const allDesignations = Array.from(new Set(members.flatMap(m => m.designations))).filter(d => d !== 'GOYA Member' && d !== '').sort();
export const allTeachingStyles = Array.from(new Set(members.flatMap(m => m.teachingStyles))).sort();
